# Generated by Django 3.1.3 on 2021-02-11 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', '男性'), ('F', '女性')], max_length=1, verbose_name='性別')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('school', models.CharField(blank=True, max_length=50, null=True, verbose_name='学歴')),
                ('address1', models.CharField(max_length=100, verbose_name='住所1')),
                ('address2', models.CharField(max_length=100, verbose_name='住所2')),
                ('register_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('last_login_datetime', models.DateTimeField(blank=True, null=True, verbose_name='最後のログインの日時')),
                ('photo', models.ImageField(upload_to='profile/', verbose_name='プロフィール')),
                ('self_disclosure', models.CharField(choices=[('T', '同意'), ('F', '拒否')], max_length=1, verbose_name='プライバシー')),
                ('attend_apply_count', models.IntegerField(default=0, verbose_name='出席申し込みの数')),
                ('actual_count', models.IntegerField(default=0, verbose_name='実際に出席した数')),
                ('introduction1', models.CharField(blank=True, max_length=4000, null=True, verbose_name='自己紹介1')),
                ('introduction2', models.CharField(blank=True, max_length=4000, null=True, verbose_name='自己紹介2')),
                ('introduction3', models.CharField(blank=True, max_length=4000, null=True, verbose_name='自己紹介3')),
                ('introduction4', models.CharField(blank=True, max_length=4000, null=True, verbose_name='自己紹介4')),
                ('introduction5', models.CharField(blank=True, max_length=4000, null=True, verbose_name='自己紹介5')),
                ('career1', models.CharField(blank=True, max_length=100, null=True, verbose_name='キャリア1')),
                ('career2', models.CharField(blank=True, max_length=100, null=True, verbose_name='キャリア2')),
                ('career3', models.CharField(blank=True, max_length=100, null=True, verbose_name='キャリア3')),
                ('career4', models.CharField(blank=True, max_length=100, null=True, verbose_name='キャリア4')),
                ('career5', models.CharField(blank=True, max_length=100, null=True, verbose_name='キャリア5')),
                ('interest1', models.CharField(max_length=50, verbose_name='気に入り1')),
                ('interest2', models.CharField(blank=True, max_length=50, null=True, verbose_name='気に入り2')),
                ('interest3', models.CharField(blank=True, max_length=50, null=True, verbose_name='気に入り3')),
                ('interest4', models.CharField(blank=True, max_length=50, null=True, verbose_name='気に入り4')),
                ('interest5', models.CharField(blank=True, max_length=50, null=True, verbose_name='気に入り5')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='経度')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_profile',
            },
        ),
    ]
